export const courseData = {
  videos: [
    {
      id: 1,
      title: "Introduction to Web Development",
      duration: "4:27",
      views: "486k",
      completed: false,
      videoId: "HfTXHrWMGVY",
    },
    {
      id: 2,
      title: "Understanding How the Web Works",
      duration: "4:20",
      views: "184k",
      completed: false,
      videoId: "88QJumITbQA",
    },
    {
      id: 3,
      title: "Your First Web Page",
      duration: "4:46",
      views: "290k",
      completed: false,
      videoId: "BvJYXl2ywUE",
    },
    {
      id: 4,
      title: "Basic HTML Elements",
      duration: "10:28",
      views: "208k",
      completed: false,
      videoId: "PypMN-yui4Y",
    },
    {
      id: 5,
      title: "Advanced HTML Elements",
      duration: "13:02",
      views: "191k",
      completed: false,
      videoId: "1rbo_HHt5nw",
    },
    {
      id: 6,
      title: "Introduction to HTML Forms",
      duration: "15:35",
      views: "137k",
      completed: false,
      videoId: "bFvjE4ZRtSE",
    },
    {
      id: 7,
      title: "Learn CSS in 20 Minutes",
      duration: "23:44",
      views: "25K",
      completed: false,
      videoId: "1PnVor36_40",
    },
    {
      id: 8,
      title: "How to Style a Modern Website Part-1",
      duration: "31:56",
      views: "1.9M",
      completed: false,
      videoId: "Sv_NAxi_jNs",
    },
    {
      id: 9,
      title: "How to Style a Modern Website Part-2",
      duration: "22:45",
      views: "260k",
      completed: false,
      videoId: "nKa1JPf0ZN4",
    },
    {
      id: 10,
      title: "How to Style a Modern Website Part-3",
      duration: "34:22",
      views: "72k",
      completed: false,
      videoId: "auWKaf0m0S0",
    },
    {
      id: 11,
      title: "JavaScript Shopping Cart Tutorial for Beginners",
      duration: "43:55",
      views: "1M",
      completed: false,
      videoId: "YeFzkC2awTM",
    },
  ],
  quizQuestions: [
    {
      id: 1,
      question: "What is the main purpose of HTML?",
      options: [
        "To structure content on web pages",
        "To style web pages",
        "To create interactive features",
        "To store data",
      ],
      correct: 0,
    },
    {
      id: 2,
      question: "Which protocol is used for transferring web pages?",
      options: ["FTP", "HTTP/HTTPS", "SMTP", "SSH"],
      correct: 1,
    },
    {
      id: 3,
      question: "What is the correct HTML element for the largest heading?",
      options: ["<heading>", "<h6>", "<head>", "<h1>"],
      correct: 3,
    },
    {
      id: 4,
      question: "Which HTML element is used to create a form?",
      options: ["<input>", "<form>", "<section>", "<div>"],
      correct: 1,
    },
    {
      id: 5,
      question: "What does CSS stand for?",
      options: [
        "Computer Style Sheets",
        "Creative Style System",
        "Cascading Style Sheets",
        "Colorful Style Sheets",
      ],
      correct: 2,
    },
  ],
  summaries: [
    "Introduction to web development fundamentals, understanding the role of frontend developers, and getting started with web technologies.",
    "Deep dive into how the internet works, understanding servers, clients, DNS, and the request-response cycle in web development.",
    "Step-by-step guide to creating your first HTML web page, understanding basic structure and essential elements.",
    "Comprehensive overview of fundamental HTML elements including paragraphs, headings, lists, and links.",
    "Exploration of advanced HTML elements like tables, semantic elements, and multimedia integration.",
    "Detailed guide to creating HTML forms, understanding different input types, and form validation.",
    "Quick but comprehensive introduction to CSS, covering selectors, properties, and basic styling concepts.",
    "Learn modern website styling techniques with practical examples - Part 1.",
    "Continue learning advanced CSS styling techniques - Part 2.",
    "Complete your modern website styling journey - Part 3.",
    "Build a functional shopping cart using JavaScript with step-by-step guidance.",
  ],
};
